package com.schreibersolutions;

/**
 * Created by dschreiber on 12/7/19.
 */
public class Constants {
    public static int[] test_program = {3,15,3,16,1002,16,10,16,1,16,15,15,4,15,99,0,0};
    public static int[] test_program2 = {3,23,3,24,1002,24,10,24,1002,23,-1,23,
            101,5,23,23,1,24,23,23,4,23,99,0,0};
    public static int[] test_program3 = {3,31,3,32,1002,32,10,32,1001,31,-2,31,1007,31,0,33,
            1002,33,7,33,1,33,31,31,1,32,31,31,4,31,99,0,0,0};

    public static String test_map = "COM)B\n" +
            "B)C\n" +
            "C)D\n" +
            "D)E\n" +
            "E)F\n" +
            "B)G\n" +
            "G)H\n" +
            "D)I\n" +
            "E)J\n" +
            "J)K\n" +
            "K)L\n" +
            "K)YOU\n" +
            "I)SAN";

    public static String orbit_map = "MQD)G37\n" +
            "MPH)V45\n" +
            "SWV)KGL\n" +
            "M5T)SG3\n" +
            "M69)788\n" +
            "MQG)RBF\n" +
            "YVM)J5B\n" +
            "GHH)G3Y\n" +
            "VS2)6L4\n" +
            "86J)15R\n" +
            "WB3)4F5\n" +
            "LVM)4P4\n" +
            "HZW)CBG\n" +
            "Q7S)1YX\n" +
            "3F1)8XQ\n" +
            "YLR)Q7J\n" +
            "9WV)JN4\n" +
            "7SN)4TX\n" +
            "6HC)P24\n" +
            "VJR)J3L\n" +
            "CMN)ZCT\n" +
            "S7C)TC3\n" +
            "JTK)ZDR\n" +
            "ZVF)49D\n" +
            "TY1)3HB\n" +
            "W6Z)PXP\n" +
            "K7H)C4J\n" +
            "LVH)XPC\n" +
            "6ZP)Q94\n" +
            "GTR)YG3\n" +
            "LHS)PWC\n" +
            "5NN)T17\n" +
            "JYL)5Y1\n" +
            "8HQ)8H6\n" +
            "RTZ)C6F\n" +
            "8NK)PS2\n" +
            "W5F)SSL\n" +
            "1SW)GQB\n" +
            "ZVR)GCP\n" +
            "GMM)ZCJ\n" +
            "QGD)K7X\n" +
            "363)KQY\n" +
            "VP9)NP3\n" +
            "8B7)H18\n" +
            "S1N)1LG\n" +
            "C3Z)XPX\n" +
            "VQ8)8T5\n" +
            "1GR)H9S\n" +
            "J6H)SCK\n" +
            "8FB)YR2\n" +
            "TJ9)BTV\n" +
            "LK7)DQB\n" +
            "SJC)DS3\n" +
            "NT9)RTR\n" +
            "PVD)WCP\n" +
            "Z55)YVM\n" +
            "N5X)1W8\n" +
            "QBL)X2B\n" +
            "SZ6)8Z8\n" +
            "1MY)YHS\n" +
            "74K)1R7\n" +
            "SK5)CVW\n" +
            "LW8)KB4\n" +
            "3YJ)F48\n" +
            "B1F)H5F\n" +
            "3J6)LDP\n" +
            "Z11)657\n" +
            "TZX)556\n" +
            "92M)DJ5\n" +
            "BC3)PJH\n" +
            "CDX)74K\n" +
            "D88)GTR\n" +
            "QNP)MV2\n" +
            "YYQ)X6B\n" +
            "DXC)NGZ\n" +
            "L7M)NRL\n" +
            "M9V)XQT\n" +
            "Z6P)S96\n" +
            "G9P)8FB\n" +
            "27V)MFP\n" +
            "994)WJV\n" +
            "B4F)WMF\n" +
            "LDG)1V2\n" +
            "8Y1)G7S\n" +
            "32W)LCB\n" +
            "KXM)9HP\n" +
            "QS9)G6H\n" +
            "FBK)H5Y\n" +
            "FRK)5V6\n" +
            "VN1)KZD\n" +
            "PH4)18P\n" +
            "RL4)7S8\n" +
            "5XJ)JSB\n" +
            "J6Z)7ZC\n" +
            "2YF)MMQ\n" +
            "6VM)M58\n" +
            "7S8)XNS\n" +
            "JTL)T9L\n" +
            "PT1)LZ3\n" +
            "D4M)5TD\n" +
            "TSP)PT4\n" +
            "PNF)6S7\n" +
            "5TV)WDP\n" +
            "SQ2)71W\n" +
            "DYV)CX2\n" +
            "RX7)9JF\n" +
            "NRW)6B3\n" +
            "2CZ)B23\n" +
            "PD7)T19\n" +
            "25H)RBY\n" +
            "YPX)38C\n" +
            "FDD)NRW\n" +
            "FBN)ZK4\n" +
            "9HP)T5B\n" +
            "K18)YSC\n" +
            "7BC)SZV\n" +
            "SRX)PWR\n" +
            "SXG)YWF\n" +
            "Z21)3L5\n" +
            "Z2H)8VK\n" +
            "B5X)S1Z\n" +
            "7Q9)11X\n" +
            "1F3)6H6\n" +
            "P7S)D6H\n" +
            "YVH)1LW\n" +
            "GGJ)FFG\n" +
            "BM2)L21\n" +
            "ZSK)92M\n" +
            "CML)3L7\n" +
            "XZ5)ZKZ\n" +
            "1HH)WS8\n" +
            "D1C)2KJ\n" +
            "GHM)SJX\n" +
            "1XZ)D63\n" +
            "XKN)KHM\n" +
            "2R9)2B7\n" +
            "VCV)JYL\n" +
            "5LN)R15\n" +
            "14J)1CC\n" +
            "5Y1)BD6\n" +
            "5P3)67Y\n" +
            "B1N)HZC\n" +
            "SCR)YDY\n" +
            "9FX)TTN\n" +
            "LWQ)18X\n" +
            "Q1M)HPX\n" +
            "17G)223\n" +
            "H8Y)W6S\n" +
            "FL1)76F\n" +
            "3LR)97C\n" +
            "H4B)LZR\n" +
            "PPD)DZB\n" +
            "VJY)WP2\n" +
            "WV8)HBY\n" +
            "MN7)WHS\n" +
            "Y1G)PL4\n" +
            "WL5)TYM\n" +
            "RQ3)4R6\n" +
            "52F)7WL\n" +
            "RJR)MK6\n" +
            "7BT)P6J\n" +
            "5FP)PVD\n" +
            "657)YR4\n" +
            "9CX)9PB\n" +
            "15R)QJ4\n" +
            "2KJ)SDN\n" +
            "G3Q)MS6\n" +
            "SDN)986\n" +
            "1J5)DHB\n" +
            "V4M)JL3\n" +
            "WGM)Q9F\n" +
            "DV4)BCM\n" +
            "9WS)GT5\n" +
            "3W4)SGG\n" +
            "7NP)GLP\n" +
            "R2V)D88\n" +
            "WQ8)58Q\n" +
            "8XB)RJD\n" +
            "QQT)9HW\n" +
            "5ST)PS8\n" +
            "4YT)J3P\n" +
            "FGX)GHN\n" +
            "S29)3TM\n" +
            "31M)F34\n" +
            "34H)CZG\n" +
            "R7M)414\n" +
            "KJ8)VQ8\n" +
            "BPB)65P\n" +
            "66X)VGS\n" +
            "44N)2W3\n" +
            "WRR)7MS\n" +
            "VXH)RRJ\n" +
            "PBK)N7R\n" +
            "GDM)44N\n" +
            "1HX)WKD\n" +
            "3YQ)S97\n" +
            "ZTH)ZQC\n" +
            "QF8)RZL\n" +
            "SJB)6R6\n" +
            "72D)R5M\n" +
            "41V)L12\n" +
            "23D)JLJ\n" +
            "D4R)K7V\n" +
            "2VV)YPX\n" +
            "NKC)4T6\n" +
            "7KQ)JFB\n" +
            "QBR)5G9\n" +
            "2FY)99T\n" +
            "C12)8PL\n" +
            "WCM)SVZ\n" +
            "3TQ)C7G\n" +
            "1F3)JCJ\n" +
            "Z3P)YYQ\n" +
            "RBF)5NN\n" +
            "WQ4)9DV\n" +
            "SSX)X4D\n" +
            "YR2)8G6\n" +
            "KLT)PT2\n" +
            "P7R)J5Y\n" +
            "78R)568\n" +
            "Z8C)5T7\n" +
            "P91)9H6\n" +
            "CNN)ZDS\n" +
            "JZN)DQC\n" +
            "211)M69\n" +
            "KXJ)B9B\n" +
            "VLJ)YQR\n" +
            "8WB)YTN\n" +
            "3TM)Z8K\n" +
            "N64)LY3\n" +
            "GKC)429\n" +
            "GTV)JT2\n" +
            "5W5)7BT\n" +
            "VGG)L5P\n" +
            "K7B)X2D\n" +
            "WRZ)5P1\n" +
            "RBG)PT1\n" +
            "JV1)LCT\n" +
            "PSV)ZKX\n" +
            "H1J)55C\n" +
            "35M)KXM\n" +
            "HTT)TJ9\n" +
            "ZG8)75V\n" +
            "6V7)FC3\n" +
            "GRV)39S\n" +
            "Y72)YXZ\n" +
            "VM4)QS5\n" +
            "95L)C5D\n" +
            "5P1)5XS\n" +
            "QQ4)6LL\n" +
            "WRK)N1N\n" +
            "XT5)6VZ\n" +
            "TRT)783\n" +
            "RQC)95N\n" +
            "769)XZM\n" +
            "QLQ)4QL\n" +
            "H5S)25Z\n" +
            "9W7)M48\n" +
            "568)5LK\n" +
            "Q3D)GD3\n" +
            "PRT)QCQ\n" +
            "WCS)FBB\n" +
            "X43)SJC\n" +
            "4QH)KGQ\n" +
            "F82)Z65\n" +
            "RJD)BBQ\n" +
            "BNN)4PD\n" +
            "3HD)7YY\n" +
            "BXC)2LN\n" +
            "2TS)MYR\n" +
            "K6V)LK7\n" +
            "551)XK6\n" +
            "9GF)WK2\n" +
            "VH8)4KM\n" +
            "3C4)HNV\n" +
            "619)8YZ\n" +
            "HF2)SWP\n" +
            "BJS)XCX\n" +
            "LR1)KSX\n" +
            "GCY)NP6\n" +
            "TC6)9RZ\n" +
            "JKP)V5N\n" +
            "3SK)FJY\n" +
            "CQX)HSW\n" +
            "DFB)Y82\n" +
            "HLS)JJ3\n" +
            "BM6)WL5\n" +
            "SFW)4JQ\n" +
            "YXZ)5SX\n" +
            "W49)27V\n" +
            "MYG)2LV\n" +
            "2NK)RL4\n" +
            "556)55P\n" +
            "MYT)CXJ\n" +
            "HW6)93R\n" +
            "HMZ)HPF\n" +
            "S95)54V\n" +
            "5LK)YF4\n" +
            "D42)T71\n" +
            "86W)BDY\n" +
            "HRN)ZX9\n" +
            "K9S)95D\n" +
            "NHQ)X5W\n" +
            "LYF)75B\n" +
            "WYK)NBT\n" +
            "YL2)SXG\n" +
            "GBV)LJD\n" +
            "JBP)Y72\n" +
            "LN2)G6G\n" +
            "6DG)BR9\n" +
            "C6Y)VKX\n" +
            "KYS)B3V\n" +
            "59B)1KZ\n" +
            "4RC)6J5\n" +
            "CWP)W5D\n" +
            "5FP)D44\n" +
            "9SF)9PN\n" +
            "1ND)Q1P\n" +
            "ZYC)D6K\n" +
            "6S7)GTP\n" +
            "K5R)S1W\n" +
            "RYX)PBK\n" +
            "JFB)F9C\n" +
            "P3J)7MQ\n" +
            "S29)8FC\n" +
            "924)T26\n" +
            "QB1)9F9\n" +
            "4ZM)G3Q\n" +
            "HGP)PD9\n" +
            "9C4)4KK\n" +
            "JR4)Q11\n" +
            "SLL)KW6\n" +
            "2W3)LJC\n" +
            "Y7C)PH4\n" +
            "KFV)T8K\n" +
            "4KM)G76\n" +
            "CZW)FPK\n" +
            "YYL)17J\n" +
            "H55)R71\n" +
            "QB1)R5D\n" +
            "KQH)WWN\n" +
            "F2R)D1K\n" +
            "WZB)T8G\n" +
            "9LK)M9T\n" +
            "PVW)ZBQ\n" +
            "V5N)BQ8\n" +
            "Z63)Z6X\n" +
            "QLH)SCR\n" +
            "7VS)TRT\n" +
            "NP6)4J9\n" +
            "YGN)TZX\n" +
            "G23)BC9\n" +
            "23S)PXY\n" +
            "QFK)CWP\n" +
            "WS5)PXV\n" +
            "KFL)CHV\n" +
            "X5V)C17\n" +
            "XBV)17L\n" +
            "783)S3S\n" +
            "GD3)YPL\n" +
            "K9L)9S7\n" +
            "48B)TGG\n" +
            "BKP)29M\n" +
            "FYB)BHM\n" +
            "YDY)7SC\n" +
            "7K1)XHR\n" +
            "GV3)B3H\n" +
            "QJV)XQQ\n" +
            "758)F4G\n" +
            "YJK)PNF\n" +
            "4MQ)7V7\n" +
            "ZVD)YTZ\n" +
            "COM)FJH\n" +
            "51M)NNL\n" +
            "JR4)LW1\n" +
            "X5W)PX5\n" +
            "P3F)BB9\n" +
            "5KT)MF4\n" +
            "GSH)YZN\n" +
            "CXW)SB3\n" +
            "N35)F3M\n" +
            "LHC)KLT\n" +
            "72K)LR9\n" +
            "F3M)F7M\n" +
            "ZBQ)934\n" +
            "SG3)NKC\n" +
            "ZVM)6R1\n" +
            "H97)C3Z\n" +
            "2YN)CML\n" +
            "QS5)25H\n" +
            "RZL)NQ5\n" +
            "DL6)9QZ\n" +
            "LR9)D29\n" +
            "Y7C)75G\n" +
            "BQ8)DK3\n" +
            "7CW)NHF\n" +
            "2D6)9GW\n" +
            "CMW)6QY\n" +
            "F4L)KKM\n" +
            "FJY)S1H\n" +
            "W45)6CG\n" +
            "9L8)TSG\n" +
            "2MQ)NMH\n" +
            "3BB)5TM\n" +
            "1LW)MQD\n" +
            "HZC)273\n" +
            "TZF)GXT\n" +
            "38C)4QS\n" +
            "XQ7)662\n" +
            "5N6)2JQ\n" +
            "7QN)9KH\n" +
            "5TM)5C9\n" +
            "PTC)27Y\n" +
            "K3H)5X8\n" +
            "FDM)N5X\n" +
            "LWF)SPT\n" +
            "8VK)R7Q\n" +
            "1C3)VJP\n" +
            "25B)YQV\n" +
            "S75)F44\n" +
            "DRX)Q93\n" +
            "B23)X41\n" +
            "B6L)DS2\n" +
            "VP4)K1V\n" +
            "C6F)ZMV\n" +
            "ZCT)VLJ\n" +
            "3MP)1DZ\n" +
            "889)MVK\n" +
            "MDR)4ZM\n" +
            "H6W)4S5\n" +
            "JR3)KFH\n" +
            "6RN)Y6T\n" +
            "V8W)7ZS\n" +
            "4QK)TZ5\n" +
            "7GW)Z11\n" +
            "H9Y)4SF\n" +
            "PWR)GHV\n" +
            "V2C)TDM\n" +
            "PWB)QPL\n" +
            "7CT)6G7\n" +
            "M2S)PD2\n" +
            "DN2)VGG\n" +
            "9CD)SNF\n" +
            "4S4)KGC\n" +
            "P5B)GRV\n" +
            "R15)BM9\n" +
            "7FC)LZN\n" +
            "JN4)31X\n" +
            "8Z8)TBM\n" +
            "DS3)QY3\n" +
            "NLS)W11\n" +
            "KQZ)XJF\n" +
            "7H3)N3H\n" +
            "QY3)QS9\n" +
            "LD6)4YT\n" +
            "6YT)9H4\n" +
            "H93)D1N\n" +
            "KL7)DPC\n" +
            "4QJ)8YV\n" +
            "75B)V2C\n" +
            "VCN)42S\n" +
            "4BN)3DC\n" +
            "7C5)CR5\n" +
            "FR3)FTC\n" +
            "RTX)ZSP\n" +
            "QJD)SJB\n" +
            "2XF)Q5S\n" +
            "63Z)HK8\n" +
            "R5M)CJQ\n" +
            "6V3)VLS\n" +
            "33W)73Q\n" +
            "ZV7)SR1\n" +
            "4N8)6K9\n" +
            "1CC)GCY\n" +
            "T19)6ZB\n" +
            "B5N)JMH\n" +
            "54Y)Z6P\n" +
            "P6J)YZ4\n" +
            "XNH)KPC\n" +
            "9D7)7SJ\n" +
            "FJF)CF2\n" +
            "SMN)8F5\n" +
            "7T4)PPB\n" +
            "BDH)RD4\n" +
            "PL4)7QW\n" +
            "CS5)51M\n" +
            "XFB)X98\n" +
            "9JF)MQG\n" +
            "XZM)H5S\n" +
            "KN1)M2P\n" +
            "XBV)XGN\n" +
            "X41)73K\n" +
            "DDK)WV8\n" +
            "TBX)BNF\n" +
            "1G1)P5T\n" +
            "V4Z)2HM\n" +
            "3CY)ZWR\n" +
            "N88)ZR2\n" +
            "XK6)XWK\n" +
            "BRN)DQJ\n" +
            "GKG)YZS\n" +
            "RL5)FS4\n" +
            "ZDS)WQ8\n" +
            "84S)FZM\n" +
            "HK8)9C4\n" +
            "NCY)9W7\n" +
            "D1N)WNS\n" +
            "XCB)RSL\n" +
            "P5N)NWH\n" +
            "S9T)KVG\n" +
            "RRD)XJP\n" +
            "6R1)VP4\n" +
            "GWV)K8G\n" +
            "DZ4)C3K\n" +
            "7T6)VPY\n" +
            "WZV)RLL\n" +
            "KT3)HRN\n" +
            "5L6)NF6\n" +
            "416)V2Y\n" +
            "YPJ)GZ3\n" +
            "DXR)GMM\n" +
            "MN9)CWH\n" +
            "DXC)Z6C\n" +
            "ZB6)15Z\n" +
            "61N)54Q\n" +
            "WNS)KYY\n" +
            "CMN)9ZD\n" +
            "8YG)K5R\n" +
            "L92)FGK\n" +
            "SJX)34C\n" +
            "P5C)BYB\n" +
            "DT6)ZPS\n" +
            "R1J)3MP\n" +
            "18X)CJY\n" +
            "2MM)CHY\n" +
            "VGL)KK7\n" +
            "V4D)H1J\n" +
            "6NT)GSN\n" +
            "65P)RP7\n" +
            "ZFY)LSX\n" +
            "G6H)1G1\n" +
            "939)R1J\n" +
            "PHK)V1Y\n" +
            "JCB)7L2\n" +
            "8N1)BF9\n" +
            "Y9R)WCM\n" +
            "LDX)2YR\n" +
            "LYC)JRH\n" +
            "9YK)9SF\n" +
            "ZK4)RWD\n" +
            "5BG)GZZ\n" +
            "3DC)31K\n" +
            "TB1)Z5Y\n" +
            "73Q)HDR\n" +
            "PD2)RTX\n" +
            "Z94)79F\n" +
            "HVW)BXP\n" +
            "745)FYB\n" +
            "WQB)JWH\n" +
            "VBP)SPH\n" +
            "3QR)3GG\n" +
            "4R1)TZF\n" +
            "DS3)HY6\n" +
            "1P2)LGZ\n" +
            "QT5)WZB\n" +
            "TRZ)BJZ\n" +
            "KTT)681\n" +
            "LJP)Q1H\n" +
            "848)M6H\n" +
            "L93)7J4\n" +
            "XLG)MCK\n" +
            "1KZ)DWJ\n" +
            "8M7)PKW\n" +
            "WKD)WWR\n" +
            "G73)CBL\n" +
            "863)DBQ\n" +
            "3Q8)CFY\n" +
            "PRH)5D1\n" +
            "CBG)9L8\n" +
            "Q6N)CFT\n" +
            "HC7)B9L\n" +
            "TG9)B4Y\n" +
            "82P)SFW\n" +
            "X5K)R76\n" +
            "9MH)CMW\n" +
            "G7S)47G\n" +
            "VKG)C61\n" +
            "9CX)S6N\n" +
            "3H8)VZX\n" +
            "95M)24G\n" +
            "P4F)QJK\n" +
            "81R)5LN\n" +
            "C4J)19Y\n" +
            "P5T)HFV\n" +
            "LTX)JR4\n" +
            "62P)C7M\n" +
            "K11)KJ6\n" +
            "KZR)1BJ\n" +
            "DNP)RBG\n" +
            "TT1)VFB\n" +
            "JNP)M3V\n" +
            "395)WZV\n" +
            "MM2)91G\n" +
            "3N9)Z5W\n" +
            "J5L)H9Y\n" +
            "W5N)J6H\n" +
            "CFR)QJB\n" +
            "YP3)6V7\n" +
            "FVL)M2Y\n" +
            "VXP)B4R\n" +
            "YW8)K7H\n" +
            "66W)RDP\n" +
            "PPF)2MM\n" +
            "QX1)6NT\n" +
            "H45)11W\n" +
            "JKK)9J1\n" +
            "MT1)WDY\n" +
            "LN9)BTK\n" +
            "JT4)YW6\n" +
            "BYB)YB5\n" +
            "YM1)HMZ\n" +
            "Z2L)L2Z\n" +
            "CST)14J\n" +
            "X9P)1BD\n" +
            "RTB)WRR\n" +
            "FZ6)Z1S\n" +
            "HQ5)63T\n" +
            "R15)M2S\n" +
            "XGQ)K6L\n" +
            "Y55)QFB\n" +
            "T1X)JTL\n" +
            "HRB)NGV\n" +
            "HPV)3RG\n" +
            "6ZP)GHH\n" +
            "QS9)74W\n" +
            "H8N)9Y6\n" +
            "14C)8NN\n" +
            "YJZ)YDW\n" +
            "CJS)WZ4\n" +
            "2PD)RH4\n" +
            "5T7)L5Q\n" +
            "5WW)12D\n" +
            "SDL)SWV\n" +
            "ZM4)HYL\n" +
            "TQG)QC7\n" +
            "N35)W45\n" +
            "GZ4)MM2\n" +
            "R7F)FBK\n" +
            "SBN)RRD\n" +
            "GXT)WF3\n" +
            "D3V)LG2\n" +
            "S7R)LN9\n" +
            "GC3)3VP\n" +
            "X4T)2D9\n" +
            "M9Z)Z44\n" +
            "6VZ)54P\n" +
            "CVW)WZF\n" +
            "LZ3)CLC\n" +
            "15P)6RN\n" +
            "7FF)Q7N\n" +
            "7VL)243\n" +
            "JYK)QP2\n" +
            "YMN)LJW\n" +
            "FH8)BFN\n" +
            "7SJ)B8Q\n" +
            "KJ6)LYD\n" +
            "BXJ)FMH\n" +
            "TKW)75J\n" +
            "D7Q)DRN\n" +
            "CBB)3H6\n" +
            "SGG)BNN\n" +
            "8Z8)9S3\n" +
            "8LV)QC1\n" +
            "CJY)RYX\n" +
            "LQ2)Y9T\n" +
            "NCY)SQF\n" +
            "DJ5)H6W\n" +
            "57Z)7SN\n" +
            "XPX)KNW\n" +
            "Y5H)RF8\n" +
            "MYT)RL5\n" +
            "FLY)6QV\n" +
            "62P)2R9\n" +
            "2Y7)QQT\n" +
            "K9D)HC7\n" +
            "6DN)716\n" +
            "DV7)7G5\n" +
            "V1M)Q3P\n" +
            "TJB)TXH\n" +
            "5XC)49P\n" +
            "QTD)CWF\n" +
            "821)1J4\n" +
            "TTN)D86\n" +
            "T41)FHL\n" +
            "Q93)GPP\n" +
            "R5R)4BS\n" +
            "PXY)N64\n" +
            "CQR)YCT\n" +
            "NYW)7RZ\n" +
            "X3C)BW5\n" +
            "5XB)QFK\n" +
            "5FQ)3TG\n" +
            "1LG)4FH\n" +
            "TB5)RCY\n" +
            "YSC)7ZB\n" +
            "MSK)W5F\n" +
            "WRK)KYS\n" +
            "YHS)1HH\n" +
            "7ZB)3YQ\n" +
            "WCL)QGD\n" +
            "P1S)SKR\n" +
            "S3S)GN3\n" +
            "SYT)S29\n" +
            "BBQ)FH6\n" +
            "TH7)86W\n" +
            "LVM)266\n" +
            "XGN)J11\n" +
            "HK8)L2B\n" +
            "DVW)1T7\n" +
            "9GW)NHG\n" +
            "1Q2)HMW\n" +
            "BF9)L32\n" +
            "J4N)L8P\n" +
            "ZZH)H2L\n" +
            "662)7NC\n" +
            "XK8)HLJ\n" +
            "L33)1ZW\n" +
            "1W8)4P9\n" +
            "9PR)H1F\n" +
            "1V2)YX3\n" +
            "KZF)SBQ\n" +
            "KYY)DS5\n" +
            "W2X)GTV\n" +
            "CQM)CL2\n" +
            "TBX)XQ5\n" +
            "JDJ)SQB\n" +
            "DGG)96S\n" +
            "VWX)MS5\n" +
            "X8P)WQ4\n" +
            "S1W)JFT\n" +
            "9S3)HVW\n" +
            "9D6)78R\n" +
            "BW5)KBJ\n" +
            "K1V)13J\n" +
            "SNF)X43\n" +
            "TTD)VGL\n" +
            "Q7J)N5R\n" +
            "1BJ)WK3\n" +
            "11W)HXZ\n" +
            "Y82)WKB\n" +
            "W6N)W8T\n" +
            "85V)WV9\n" +
            "WMF)F1Y\n" +
            "SK1)HP1\n" +
            "TVC)NSV\n" +
            "KGC)66W\n" +
            "T1V)SK1\n" +
            "HKF)SXS\n" +
            "95L)GBV\n" +
            "7CL)W49\n" +
            "YTZ)8R6\n" +
            "FJ7)HN9\n" +
            "2NB)GTN\n" +
            "SSL)M3H\n" +
            "JV8)SQL\n" +
            "D7N)TSQ\n" +
            "XTL)QPX\n" +
            "JYL)956\n" +
            "W6S)XZ5\n" +
            "V1G)6ZY\n" +
            "HC2)MM1\n" +
            "6QP)3CY\n" +
            "7KW)DDK\n" +
            "4HV)Z2J\n" +
            "GHV)KTT\n" +
            "829)32W\n" +
            "5R9)X4F\n" +
            "7J5)Y8W\n" +
            "9F9)GTT\n" +
            "49P)ZL4\n" +
            "D2V)SAN\n" +
            "L2W)DYV\n" +
            "6H6)TZM\n" +
            "HVJ)K9R\n" +
            "KPJ)BC3\n" +
            "25Z)JZY\n" +
            "5V6)5R4\n" +
            "JZY)5ST\n" +
            "1F1)CS5\n" +
            "N53)ZDN\n" +
            "9G8)181\n" +
            "DPC)PB4\n" +
            "1SP)48B\n" +
            "95F)XMT\n" +
            "Q8W)HBM\n" +
            "J4H)R7F\n" +
            "D7T)TXM\n" +
            "CQR)X3C\n" +
            "7C6)FHH\n" +
            "1V2)CP6\n" +
            "X7L)9PS\n" +
            "F3F)Z8X\n" +
            "HNM)NB7\n" +
            "GW7)X69\n" +
            "D1K)4XP\n" +
            "F7D)HNM\n" +
            "SDX)2ZR\n" +
            "HHS)BY3\n" +
            "NK9)52X\n" +
            "1C5)CJS\n" +
            "GBQ)JV9\n" +
            "7SL)KY3\n" +
            "6CG)2XQ\n" +
            "7YY)X85\n" +
            "7B7)DT6\n" +
            "JCJ)72D\n" +
            "KSX)K9D\n" +
            "2ZL)T5Q\n" +
            "4BQ)QBR\n" +
            "9H5)SBN\n" +
            "5PV)L56\n" +
            "7WW)745\n" +
            "5W8)JZN\n" +
            "JRH)VK3\n" +
            "D6K)T7Q\n" +
            "SWF)J7T\n" +
            "5TD)S1N\n" +
            "6GM)2Q2\n" +
            "FJH)XLG\n" +
            "XWK)Q1M\n" +
            "NN2)8SY\n" +
            "7DP)FLB\n" +
            "QFB)YLR\n" +
            "MVK)K3L\n" +
            "F1Y)Z93\n" +
            "VP6)359\n" +
            "KVG)93K\n" +
            "YTN)2Q9\n" +
            "S11)FJF\n" +
            "1K3)R6H\n" +
            "8DD)D4R\n" +
            "H5F)Z94\n" +
            "4YC)QMW\n" +
            "NYQ)NLQ\n" +
            "YPJ)KPJ\n" +
            "93R)ZVR\n" +
            "5SX)31Z\n" +
            "V2H)9PR\n" +
            "D8L)T4F\n" +
            "FGB)343\n" +
            "Q79)9WS\n" +
            "Y76)BGD\n" +
            "97S)NLS\n" +
            "MQG)ZTH\n" +
            "D29)T1V\n" +
            "575)QLQ\n" +
            "WDY)LDG\n" +
            "2RM)926\n" +
            "BNF)S11\n" +
            "X59)6C4\n" +
            "CPN)GDY\n" +
            "WYL)3HR\n" +
            "XGS)4R1\n" +
            "Q6G)LVV\n" +
            "RTZ)M5T\n" +
            "VDQ)QZ9\n" +
            "278)3RV\n" +
            "VG2)CCD\n" +
            "Q3P)HW6\n" +
            "B2P)7BD\n" +
            "LSX)MKF\n" +
            "LZN)2Y7\n" +
            "6TV)7CL\n" +
            "9YP)BJS\n" +
            "HN9)T91\n" +
            "QBW)XZ8\n" +
            "9GN)9SV\n" +
            "JLF)ZY1\n" +
            "6ZS)1BY\n" +
            "RWD)TZQ\n" +
            "MMQ)WXH\n" +
            "7MR)GHM\n" +
            "WV9)W4Z\n" +
            "3J9)XSB\n" +
            "Q11)QBW\n" +
            "63T)GV3\n" +
            "X2B)K2G\n" +
            "MN7)BPJ\n" +
            "RF8)52F\n" +
            "4QL)H4B\n" +
            "JMM)2G4\n" +
            "B9B)Z7P\n" +
            "4JQ)XFX\n" +
            "V17)ZB6\n" +
            "YJM)95F\n" +
            "WYF)V9Z\n" +
            "Z6X)JBK\n" +
            "GCP)B9P\n" +
            "S8H)XXK\n" +
            "ZCJ)P7R\n" +
            "1NV)V4D\n" +
            "Y3N)5TV\n" +
            "CHY)84S\n" +
            "LTK)96G\n" +
            "MY2)PKT\n" +
            "JDP)Z8C\n" +
            "3L7)GQL\n" +
            "JT2)BDV\n" +
            "GK8)5PV\n" +
            "PK8)F2R\n" +
            "XGQ)GMN\n" +
            "DL2)NYQ\n" +
            "JWH)D7Q\n" +
            "MK7)QHJ\n" +
            "NTX)HC1\n" +
            "KW6)VX3\n" +
            "LW1)6FK\n" +
            "8H6)JDP\n" +
            "YL8)1LR\n" +
            "B4Z)P98\n" +
            "54K)J4H\n" +
            "QSQ)ZFY\n" +
            "Z71)FDM\n" +
            "KGQ)D7T\n" +
            "FFG)T6N\n" +
            "2GT)DQ8\n" +
            "W5N)C51\n" +
            "BWM)DNQ\n" +
            "2TL)YQ9\n" +
            "MTJ)645\n" +
            "7HX)VSC\n" +
            "V45)XN6\n" +
            "GMN)54Y\n" +
            "ZK4)G9F\n" +
            "4XP)C76\n" +
            "Z1Y)RLQ\n" +
            "DB4)T4N\n" +
            "88L)YJM\n" +
            "KC3)WQP\n" +
            "T79)L93\n" +
            "5JS)GFF\n" +
            "C3K)8F6\n" +
            "D5W)B5X\n" +
            "1ZW)WGM\n" +
            "39S)517\n" +
            "ZL4)4RC\n" +
            "JLB)JYY\n" +
            "B68)RBC\n" +
            "CM2)SL7\n" +
            "T8G)YVF\n" +
            "DFB)PGM\n" +
            "GPP)9CX\n" +
            "S2Z)55L\n" +
            "T56)8GW\n" +
            "3RV)JDJ\n" +
            "DD2)Z21\n" +
            "YZ4)MN9\n" +
            "55L)ZJL\n" +
            "WLT)M84\n" +
            "1Q2)P5C\n" +
            "SMB)T79\n" +
            "514)841\n" +
            "C94)S4Z\n" +
            "BR9)XQ7\n" +
            "B3V)B1F\n" +
            "YCN)7VZ\n" +
            "FB7)TH8\n" +
            "YZ2)THZ\n" +
            "X2Q)6V3\n" +
            "D8G)95L\n" +
            "D1N)Q1J\n" +
            "LFX)YYL\n" +
            "SVZ)Y76\n" +
            "RCY)DWD\n" +
            "BTK)PGN\n" +
            "VC4)8VQ\n" +
            "2RD)PYH\n" +
            "JMH)JQL\n" +
            "SQF)LVM\n" +
            "CBY)GS5\n" +
            "G7Z)NN2\n" +
            "VLL)CBY\n" +
            "LHS)XQF\n" +
            "8GW)QM5\n" +
            "4TH)LW5\n" +
            "7SC)7C6\n" +
            "YG3)Z1Y\n" +
            "3TK)8KS\n" +
            "RBY)NZJ\n" +
            "CQ7)1F3\n" +
            "2R5)7XG\n" +
            "RPL)HF2\n" +
            "71W)S9T\n" +
            "ZQC)YYD\n" +
            "PKW)17T\n" +
            "QPL)HTT\n" +
            "KMB)GS4\n" +
            "LDP)Q9J\n" +
            "S3J)25B\n" +
            "K6Q)3MD\n" +
            "Z42)VCV\n" +
            "956)9V8\n" +
            "4NH)DFB\n" +
            "GJ6)2CZ\n" +
            "J11)C6V\n" +
            "4PD)3YJ\n" +
            "QNG)GW7\n" +
            "67P)NM7\n" +
            "QZL)G1M\n" +
            "J33)Q28\n" +
            "XFX)CDC\n" +
            "QP2)TRZ\n" +
            "ZPJ)8QG\n" +
            "KHM)WLD\n" +
            "FHH)JKV\n" +
            "VGV)46M\n" +
            "5X8)XBV\n" +
            "55P)ZFF\n" +
            "1DX)LK3\n" +
            "861)4QH\n" +
            "5D1)MK7\n" +
            "6LL)NWC\n" +
            "F4G)GHY\n" +
            "FRN)QDD\n" +
            "4MT)9H5\n" +
            "65P)4GS\n" +
            "GQL)QTD\n" +
            "LDL)H8T\n" +
            "CXJ)VHG\n" +
            "FTC)591\n" +
            "VV6)QZ1\n" +
            "1J4)TJL\n" +
            "1DM)FL1\n" +
            "FL1)NNT\n" +
            "JFD)9FX\n" +
            "XVS)TTD\n" +
            "Q1P)X5K\n" +
            "429)CXF\n" +
            "75V)D8L\n" +
            "XQT)5W8\n" +
            "5ZR)LVY\n" +
            "WK4)7B7\n" +
            "C7Z)BB7\n" +
            "QHJ)LHS\n" +
            "PJH)JD3\n" +
            "17J)WRK\n" +
            "J5B)JMM\n" +
            "MF4)CRF\n" +
            "QT6)JV8\n" +
            "XCD)2XD\n" +
            "WD6)389\n" +
            "DFV)L9D\n" +
            "FYP)C55\n" +
            "KRP)8M7\n" +
            "ZFZ)LVD\n" +
            "LTK)MSK\n" +
            "MPT)D8G\n" +
            "QJB)T25\n" +
            "HCP)BSM\n" +
            "DQ8)W12\n" +
            "H18)ZVM\n" +
            "M7P)R2P\n" +
            "NM7)CXR\n" +
            "GJW)9MH\n" +
            "VPY)22Q\n" +
            "THZ)TY1\n" +
            "4JQ)W69\n" +
            "GV4)MD5\n" +
            "4F6)XYV\n" +
            "YR4)6JT\n" +
            "5MN)NGY\n" +
            "4K2)7H3\n" +
            "WZB)YYB\n" +
            "8YV)Q6N\n" +
            "XN6)FH8\n" +
            "DQB)3FB\n" +
            "HBM)J8R\n" +
            "223)WBH\n" +
            "1M4)KT3\n" +
            "CCD)ZRN\n" +
            "Y8M)5BW\n" +
            "FS4)WB3\n" +
            "YVF)XH5\n" +
            "PB4)H7X\n" +
            "9J1)PF1\n" +
            "X6B)MZX\n" +
            "XQ5)6WM\n" +
            "57Z)P7S\n" +
            "V49)P91\n" +
            "8LV)TJB\n" +
            "N5R)ZVF\n" +
            "WS8)XRT\n" +
            "X4K)8KZ\n" +
            "YQ9)SZS\n" +
            "Y6T)Z2L\n" +
            "2HP)1BS\n" +
            "ZTH)5W5\n" +
            "PSX)P32\n" +
            "WWT)8WB\n" +
            "QV9)QBL\n" +
            "986)3RY\n" +
            "MQT)CQX\n" +
            "C51)HGP\n" +
            "DQJ)7JW\n" +
            "QL3)DFV\n" +
            "Q9M)Y7Z\n" +
            "QZ1)YMN\n" +
            "P1Y)584\n" +
            "T91)83M\n" +
            "FH6)FGX\n" +
            "QLJ)N53\n" +
            "R5D)VM4\n" +
            "8SY)67P\n" +
            "N3F)363\n" +
            "HBY)SK5\n" +
            "V1Y)X8P\n" +
            "Y31)63Z\n" +
            "3JF)1F1\n" +
            "6G7)9B8\n" +
            "3JF)6QP\n" +
            "KB4)3SC\n" +
            "95D)RTB\n" +
            "591)S7R\n" +
            "5P1)9YK\n" +
            "H9F)P3F\n" +
            "6QV)LR7\n" +
            "WQN)7BC\n" +
            "R5H)K5P\n" +
            "JJ3)CMY\n" +
            "25M)QQ4\n" +
            "NP3)DL2\n" +
            "KDY)TKC\n" +
            "QMN)B85\n" +
            "R7W)YOU\n" +
            "Q9J)YNH\n" +
            "Q2G)SXK\n" +
            "C5M)GKG\n" +
            "XQQ)KLM\n" +
            "W4Z)BDH\n" +
            "X3T)QF8\n" +
            "7ZV)939\n" +
            "PS2)5XB\n" +
            "PX5)4QK\n" +
            "R6H)351\n" +
            "5HH)5JS\n" +
            "9MH)848\n" +
            "235)D2V\n" +
            "VJP)WWT\n" +
            "TG7)7CT\n" +
            "9M3)PPF\n" +
            "GQM)29Z\n" +
            "CZG)SNW\n" +
            "DQ1)66N\n" +
            "PK9)GKW\n" +
            "B4R)QZL\n" +
            "256)WTQ\n" +
            "645)H8H\n" +
            "G1G)29X\n" +
            "8BZ)TG6\n" +
            "YCZ)N1J\n" +
            "N88)G9P\n" +
            "VQR)DQ1\n" +
            "VC4)Y31\n" +
            "FH8)WYK\n" +
            "66N)4MF\n" +
            "CJY)Y8T\n" +
            "9PB)LDL\n" +
            "882)JNX\n" +
            "58Q)89M\n" +
            "2MQ)FJ5\n" +
            "V5X)DV7\n" +
            "XNH)76D\n" +
            "RDP)1T2\n" +
            "31Z)S95\n" +
            "4J9)KQ3\n" +
            "LCT)C6J\n" +
            "K9L)R3P\n" +
            "9B7)8LV\n" +
            "7FT)77G\n" +
            "7ZC)SNP\n" +
            "HP1)HWZ\n" +
            "S4Z)4WP\n" +
            "M58)TQ5\n" +
            "P6L)4N8\n" +
            "SNW)FKT\n" +
            "56J)J5D\n" +
            "ZQC)VN1\n" +
            "X69)882\n" +
            "8D4)155\n" +
            "3Y1)8M4\n" +
            "M5L)4TH\n" +
            "M48)V1G\n" +
            "WK2)M6B\n" +
            "18X)XR6\n" +
            "QJK)RLK\n" +
            "W12)Q2G\n" +
            "7RZ)4Y3\n" +
            "KPC)5S8\n" +
            "NNL)7NV\n" +
            "X8Y)4G8\n" +
            "6QY)XZG\n" +
            "NMH)SYT\n" +
            "9KH)SKB\n" +
            "BKW)Y5H\n" +
            "XJF)VKG\n" +
            "8M4)WT2\n" +
            "T8K)SMB\n" +
            "BY5)994\n" +
            "BB9)L38\n" +
            "QVT)SCX\n" +
            "4T6)2SZ\n" +
            "9D3)KFL\n" +
            "584)6ZP\n" +
            "PPM)S8H\n" +
            "19K)NYZ\n" +
            "W8Z)RJR\n" +
            "ZMV)7KW\n" +
            "45T)YK9\n" +
            "KY3)Q2N\n" +
            "Z6C)9LK\n" +
            "CLC)7FC\n" +
            "CRF)N44\n" +
            "GMN)C5M\n" +
            "XQ5)R8G\n" +
            "9Y6)HMX\n" +
            "Z7X)JY5\n" +
            "79G)2YN\n" +
            "B79)F8D\n" +
            "CD2)S2Z\n" +
            "DN1)FR3\n" +
            "K8G)D9R\n" +
            "LGH)WYL\n" +
            "1DZ)DD2\n" +
            "11X)3JX\n" +
            "WF3)FB7\n" +
            "273)V49\n" +
            "5BW)HT2\n" +
            "3VQ)FGB\n" +
            "8BZ)1K3\n" +
            "JXV)ZG8\n" +
            "QQK)KJ8\n" +
            "PZC)YZ2\n" +
            "WLD)P5N\n" +
            "QKT)619\n" +
            "JL3)DPG\n" +
            "6J8)CMN\n" +
            "72K)LDB\n" +
            "R1W)V8W\n" +
            "T4F)6VM\n" +
            "ZKX)QZ2\n" +
            "CVJ)CRK\n" +
            "B85)8SZ\n" +
            "DH3)P5B\n" +
            "WLT)9SH\n" +
            "N7R)DPR\n" +
            "T9L)1P2\n" +
            "4R6)PD7\n" +
            "TMV)X5V\n" +
            "MS5)PHK\n" +
            "1GP)CP8\n" +
            "3SC)M4K\n" +
            "DRW)6JS\n" +
            "9PN)2NK\n" +
            "LVV)BCH\n" +
            "CML)23S\n" +
            "4SF)WCL\n" +
            "L7M)Q27\n" +
            "9PS)7C5\n" +
            "JL3)VWC\n" +
            "1BD)7WW\n" +
            "NGY)QSY\n" +
            "M91)CM2\n" +
            "V24)DV4\n" +
            "S97)TKW\n" +
            "HLJ)4T9\n" +
            "WTG)P1S\n" +
            "JV9)J2B\n" +
            "KKM)2XF\n" +
            "R2P)3C4\n" +
            "4P4)2GT\n" +
            "M9C)3J6\n" +
            "94G)HKF\n" +
            "KQ7)GFY\n" +
            "5WW)6ZS\n" +
            "DPG)85V\n" +
            "SZ6)QNP\n" +
            "JFJ)6XD\n" +
            "T19)HRB\n" +
            "RYS)6GD\n" +
            "2Q2)DH3\n" +
            "MZX)Z7X\n" +
            "5H5)QX2\n" +
            "PXP)FJ7\n" +
            "V52)X8F\n" +
            "Y6C)S7C\n" +
            "H81)KB9\n" +
            "BDY)6YT\n" +
            "B9P)3CQ\n" +
            "KGD)M9Z\n" +
            "8Y1)4MT\n" +
            "GW2)KD2\n" +
            "4HV)CQR\n" +
            "VG8)6NW\n" +
            "PGN)M6Y\n" +
            "LTH)MB4\n" +
            "FT1)PPD\n" +
            "XH5)GSH\n" +
            "SCK)ZSK\n" +
            "9B8)YW8\n" +
            "HLX)JNP\n" +
            "YF4)VH8\n" +
            "4S5)KRP\n" +
            "W37)TB1\n" +
            "5YT)D3V\n" +
            "6ZH)CPN\n" +
            "4LF)9RX\n" +
            "L56)1SP\n" +
            "CXR)3RN\n" +
            "Q1J)F4D\n" +
            "KFH)R7W\n" +
            "BPJ)JLF\n" +
            "D86)XVS\n" +
            "GF9)5ZR\n" +
            "H1F)TD9\n" +
            "74W)V2H\n" +
            "M3V)842\n" +
            "9S7)Z55\n" +
            "M4K)8Y1\n" +
            "TTM)79G\n" +
            "97C)WXR\n" +
            "PWN)VV6\n" +
            "SZV)1CJ\n" +
            "3LH)S59\n" +
            "T2J)W44\n" +
            "5XS)SJN\n" +
            "YVK)BJF\n" +
            "R5K)FW2\n" +
            "395)2TL\n" +
            "GSN)M8S\n" +
            "MQT)H9F\n" +
            "842)TH7\n" +
            "PXY)QHG\n" +
            "DL2)1YF\n" +
            "5Q2)X59\n" +
            "V15)JV1\n" +
            "X9K)YQK\n" +
            "MFN)HWF\n" +
            "Q94)QVM\n" +
            "GTP)32S\n" +
            "BJN)CFR\n" +
            "6JT)FSF\n" +
            "JDK)X7L\n" +
            "SZS)FBN\n" +
            "15R)R1W\n" +
            "DDK)59B\n" +
            "681)7FM\n" +
            "Z72)PH5\n" +
            "5GD)BXJ\n" +
            "B4Y)GV4\n" +
            "5G9)X44\n" +
            "S64)7MR\n" +
            "JHS)821\n" +
            "YHS)T7J\n" +
            "KD2)KMB\n" +
            "PXV)4HV\n" +
            "DK3)4YC\n" +
            "S79)823\n" +
            "F4D)2RM\n" +
            "MD5)DGG\n" +
            "3H6)FT1\n" +
            "17L)KXJ\n" +
            "NLZ)N35\n" +
            "ZWR)X8Y\n" +
            "HMW)K9S\n" +
            "W8Z)M2T\n" +
            "38C)NK9\n" +
            "GKW)1VV\n" +
            "P98)LD6\n" +
            "WBH)3WV\n" +
            "QLQ)H16\n" +
            "WXH)7TR\n" +
            "J7T)5H2\n" +
            "TXH)VLQ\n" +
            "HXZ)QW2\n" +
            "NT6)94P\n" +
            "YW9)R5H\n" +
            "VK3)QKT\n" +
            "SN2)QDS\n" +
            "JXM)QT5\n" +
            "76D)MN7\n" +
            "7L2)PRT\n" +
            "99Y)BKP\n" +
            "3W4)YY3\n" +
            "46M)15C\n" +
            "JLJ)15P\n" +
            "CDC)MYT\n" +
            "BM9)LYF\n" +
            "GZZ)SDX\n" +
            "X1K)V81\n" +
            "TYH)9CD\n" +
            "2JQ)GC3\n" +
            "HJ2)X9D\n" +
            "QJ4)4KR\n" +
            "8SZ)ZTV\n" +
            "3MX)3KX\n" +
            "K3Q)278\n" +
            "GHH)TBX\n" +
            "3WV)SN2\n" +
            "JKV)ZQF\n" +
            "C12)Z8N\n" +
            "1YX)79V\n" +
            "WTQ)SQV\n" +
            "L21)TXC\n" +
            "59B)56J\n" +
            "S1H)Y9D\n" +
            "Y73)BM2\n" +
            "BC9)M7N\n" +
            "QM5)LWQ\n" +
            "PKT)L2W\n" +
            "5W8)8GJ\n" +
            "6L4)5XC\n" +
            "Z88)7NP\n" +
            "7X1)P4F\n" +
            "N73)5KT\n" +
            "4QH)VWX\n" +
            "23G)PZC\n" +
            "X8F)KM8\n" +
            "42S)YW5\n" +
            "QCQ)8QV\n" +
            "7ZR)CQM\n" +
            "H94)X9J\n" +
            "S1Z)MYG\n" +
            "4T9)NYW\n" +
            "P2J)PK9\n" +
            "L1H)7FT\n" +
            "4GS)YW9\n" +
            "ZX9)928\n" +
            "RD4)423\n" +
            "SY7)NHQ\n" +
            "NJ7)T41\n" +
            "T71)Q79\n" +
            "H6X)Y7C\n" +
            "7ZX)B5N\n" +
            "CMT)J6C\n" +
            "4P9)RYS\n" +
            "DS2)XPP\n" +
            "V2Y)8D4\n" +
            "GWY)XS8\n" +
            "Z8N)6GM\n" +
            "NSR)5WW\n" +
            "RH4)LGH\n" +
            "PH8)Z42\n" +
            "SQL)GQM\n" +
            "MZG)GW2\n" +
            "C76)MFN\n" +
            "C6J)F2V\n" +
            "6NQ)DN1\n" +
            "XPC)3H7\n" +
            "XQF)NT6\n" +
            "VCQ)5KL\n" +
            "YQR)XT5\n" +
            "JKD)FDD\n" +
            "1BS)7VS\n" +
            "K7X)1GP\n" +
            "KGL)W5N\n" +
            "BH3)26W\n" +
            "W8T)W3Y\n" +
            "4G8)1S2\n" +
            "2YR)YCD\n" +
            "VSL)LN2\n" +
            "7JW)KGD\n" +
            "SPT)PWN\n" +
            "8T5)G2W\n" +
            "55C)6BG\n" +
            "D95)B6L\n" +
            "GN3)769\n" +
            "PPB)XFB\n" +
            "Y8W)VDQ\n" +
            "WWR)7T6\n" +
            "YQ7)SDL\n" +
            "1D2)XNH\n" +
            "BFG)3TK\n" +
            "7T3)5N6\n" +
            "MK6)GZ6\n" +
            "8F5)VJR\n" +
            "VLS)DVL\n" +
            "WKK)FYP\n" +
            "F6C)KQ7\n" +
            "VLQ)ZPJ\n" +
            "3MD)Q7S\n" +
            "TJ6)JFD\n" +
            "SGY)H45\n" +
            "16V)42V\n" +
            "J5Y)F82\n" +
            "QT6)M5L\n" +
            "W45)RQ3\n" +
            "PW5)8NK\n" +
            "V9Z)NHZ\n" +
            "LR1)7ZV\n" +
            "G37)G23\n" +
            "BD6)NTX\n" +
            "PL9)PSV\n" +
            "TB5)BRN\n" +
            "LJC)ZQN\n" +
            "Q5S)PN8\n" +
            "CB7)7ZR\n" +
            "GGS)V1R\n" +
            "ZSP)R3L\n" +
            "H8H)GKC\n" +
            "3BR)1D2\n" +
            "NWN)NCY\n" +
            "NR7)WCT\n" +
            "TXC)S2T\n" +
            "PZC)GF9\n" +
            "47G)TNB\n" +
            "G6G)YWP\n" +
            "N1J)HV8\n" +
            "6ZB)M9V\n" +
            "R76)WYF\n" +
            "QPX)51Q\n" +
            "ZRP)WHX\n" +
            "ZBM)L5G\n" +
            "C6V)K9L\n" +
            "N28)JKP\n" +
            "3VP)W6Z\n" +
            "BTV)XK8\n" +
            "PN8)4SN\n" +
            "838)6L9\n" +
            "87D)H3B\n" +
            "BZK)VJY\n" +
            "TKC)FTY\n" +
            "CXF)4LF\n" +
            "WZS)416\n" +
            "XR6)MZG\n" +
            "YCD)S64\n" +
            "N44)89S\n" +
            "4SF)V52\n" +
            "T4N)WQB\n" +
            "GTN)5W9\n" +
            "RK3)72K\n" +
            "94P)JT4\n" +
            "2HM)1PN\n" +
            "C5D)Z2X\n" +
            "MFP)N3F\n" +
            "9YP)BM6\n" +
            "N7H)BY5\n" +
            "YDW)9M3\n" +
            "D44)L1H\n" +
            "HRN)XGS\n" +
            "YTP)X9K\n" +
            "QKT)QT7\n" +
            "W69)H8Y\n" +
            "XJP)7VL\n" +
            "STJ)JVH\n" +
            "QT7)H8N\n" +
            "Z42)BFG\n" +
            "NQ5)VXP\n" +
            "14F)LFX\n" +
            "J8R)YTP\n" +
            "9Y6)L8K\n" +
            "GZ6)2NB\n" +
            "QJ4)DXR\n" +
            "89S)QQK\n" +
            "WXR)CQ7\n" +
            "LVD)DB4\n" +
            "Y55)19K\n" +
            "NGR)FRN\n" +
            "9MT)XCD\n" +
            "F9X)M9C\n" +
            "7FF)92Q\n" +
            "PN7)21G\n" +
            "8KZ)JH4\n" +
            "SB3)3LH\n" +
            "77G)3VQ\n" +
            "2ZR)GGJ\n" +
            "QT7)C7Z\n" +
            "7P7)4K2\n" +
            "S6N)STX\n" +
            "M84)TG9\n" +
            "QH8)QVT\n" +
            "QX1)63X\n" +
            "T7J)SKF\n" +
            "BHM)HJ2\n" +
            "12D)5NY\n" +
            "Q1H)68X\n" +
            "Q3K)Z72\n" +
            "B8Q)9YQ\n" +
            "HYL)P9T\n" +
            "QR6)62P\n" +
            "CF2)JXV\n" +
            "YZS)M91\n" +
            "9B7)9SX\n" +
            "9SH)LYC\n" +
            "K9R)2D6\n" +
            "8R6)X6F\n" +
            "GLP)G9H\n" +
            "34Y)YPJ\n" +
            "NTZ)4TC\n" +
            "389)ZPY\n" +
            "517)N73\n" +
            "DQ1)Y3N\n" +
            "HNV)8YG\n" +
            "KZF)2ZL\n" +
            "1RK)PN2\n" +
            "H8T)R7M\n" +
            "3Y2)WK4\n" +
            "4QS)2WC\n" +
            "NX9)VCN\n" +
            "KTD)GW6\n" +
            "NKW)VSL\n" +
            "C7M)6DN\n" +
            "HMX)X2Q\n" +
            "X4F)X6P\n" +
            "6FC)31M\n" +
            "4FH)256\n" +
            "51F)6NQ\n" +
            "L2B)PL9\n" +
            "J2B)3V5\n" +
            "YYB)RPL\n" +
            "5BW)M8X\n" +
            "CJQ)VG8\n" +
            "Z5W)ZWH\n" +
            "8JZ)Q3K\n" +
            "RF8)NT9\n" +
            "G1M)2PD\n" +
            "JD3)JXM\n" +
            "KZD)86J\n" +
            "WY2)BPB\n" +
            "KSN)QJD\n" +
            "ZP1)TC6\n" +
            "YY3)X9P\n" +
            "JY5)C6Y\n" +
            "54Q)5XJ\n" +
            "32S)GKK\n" +
            "6JS)BWM\n" +
            "72M)QBH\n" +
            "54V)W6N\n" +
            "W11)7T4\n" +
            "YB5)5GS\n" +
            "BJF)WKV\n" +
            "P2X)QJV\n" +
            "Z2J)MSD\n" +
            "M7N)L33\n" +
            "8RZ)57Z\n" +
            "CBL)95M\n" +
            "WCL)8HQ\n" +
            "8QV)35M\n" +
            "TSQ)72M\n" +
            "VGS)4LJ\n" +
            "PT2)235\n" +
            "9SV)HVJ\n" +
            "1YF)9D7\n" +
            "BDV)DBN\n" +
            "13J)ZVD\n" +
            "ZCH)9YP\n" +
            "KB9)25M\n" +
            "LQ3)Q7H\n" +
            "BCH)VG2\n" +
            "DRN)VLL\n" +
            "6GD)34Y\n" +
            "54Y)7KQ\n" +
            "DJ5)GJW\n" +
            "X6F)5BG\n" +
            "5RJ)QV9\n" +
            "C6J)S3V\n" +
            "8N1)S79\n" +
            "HSW)33W\n" +
            "841)4QJ\n" +
            "18P)R1D\n" +
            "PGM)DN2\n" +
            "L9D)NLZ\n" +
            "LDG)WRH\n" +
            "QY3)1M3\n" +
            "WC9)14C\n" +
            "9HW)ZPK\n" +
            "NHF)YQ7\n" +
            "KGZ)X73\n" +
            "889)HHS\n" +
            "42V)M9Y\n" +
            "Q6P)V24\n" +
            "48M)DZT\n" +
            "DZ4)5MN\n" +
            "2Q9)LVH\n" +
            "SBQ)WC9\n" +
            "MZH)59N\n" +
            "7XG)KVN\n" +
            "6DN)57K\n" +
            "22Q)8M2\n" +
            "CXX)6FC\n" +
            "MK7)YM1\n" +
            "TNB)Y4Z\n" +
            "S7C)41V\n" +
            "GS5)7K9\n" +
            "CX2)SMN\n" +
            "1LR)395\n" +
            "QQX)GD7\n" +
            "FLB)16V\n" +
            "TD9)6CK\n" +
            "TKC)97S\n" +
            "6XD)X1K\n" +
            "5W5)9G8\n" +
            "J4H)LW8\n" +
            "SKR)N7H\n" +
            "7H3)WKK\n" +
            "WYD)NJ7\n" +
            "7J4)5YT\n" +
            "181)Y6C\n" +
            "TGG)RHD\n" +
            "4TC)B4J\n" +
            "M6Y)B4Z\n" +
            "WRH)F8N\n" +
            "BGD)3MX\n" +
            "GHV)YJK\n" +
            "GNQ)WH8\n" +
            "VSC)45T\n" +
            "2XD)62Z\n" +
            "JRW)JDK\n" +
            "TCH)D4M\n" +
            "WQP)ZFZ\n" +
            "K5P)PH8\n" +
            "8KS)2HP\n" +
            "3L5)DZ4\n" +
            "YSC)B7X\n" +
            "1S2)GGS\n" +
            "LDB)CDX\n" +
            "9CD)S9W\n" +
            "YQK)R5K\n" +
            "L8K)1ND\n" +
            "4MF)TQG\n" +
            "VHG)SQ2\n" +
            "F34)CDS\n" +
            "91G)GNQ\n" +
            "5S8)JHS\n" +
            "KXL)DTY\n" +
            "BFN)GK8\n" +
            "M6H)54K\n" +
            "79F)W7D\n" +
            "JH4)MZH\n" +
            "99T)V1M\n" +
            "KGD)23G\n" +
            "W5D)JTK\n" +
            "3RN)D1C\n" +
            "KJL)7GW\n" +
            "9KY)5NB\n" +
            "RPV)14F\n" +
            "GKK)X4T\n" +
            "BPM)M85\n" +
            "2NB)LQ3\n" +
            "M3H)94G\n" +
            "J92)7QN\n" +
            "Z93)B1N\n" +
            "NRL)VCQ\n" +
            "31X)Y1G\n" +
            "5CB)8XB\n" +
            "9H6)9MD\n" +
            "24G)NHX\n" +
            "DNQ)SST\n" +
            "ZWH)5GD\n" +
            "DS5)453\n" +
            "Q28)BXC\n" +
            "934)6TV\n" +
            "YX3)6DG\n" +
            "9V8)QB1\n" +
            "M2P)KXL\n" +
            "TXM)K9K\n" +
            "H9S)8JZ\n" +
            "YBG)HFM\n" +
            "3TG)TCH\n" +
            "NYZ)3F1\n" +
            "3V5)KJL\n" +
            "MB4)NX9\n" +
            "DPR)9TX\n" +
            "MSK)6ZH\n" +
            "7K9)5FQ\n" +
            "S9W)NTZ\n" +
            "GFF)Y73\n" +
            "S7R)468\n" +
            "T6N)BJ4\n" +
            "M2P)R8M\n" +
            "PYH)HZ1\n" +
            "GZ3)6HC\n" +
            "CP6)QQH\n" +
            "STX)7SL\n" +
            "4Y3)K11\n" +
            "SQF)CNN\n" +
            "JFT)LJP\n" +
            "FPK)5P3\n" +
            "X44)MQT\n" +
            "G3Y)2RD\n" +
            "QZ2)9DL\n" +
            "54P)VXH\n" +
            "DTY)XZS\n" +
            "C94)P6L\n" +
            "SQV)3SK\n" +
            "QSY)SRX\n" +
            "DZT)F4L\n" +
            "YW5)KFV\n" +
            "2G4)W2X\n" +
            "1W8)HC2\n" +
            "RN6)Q4M\n" +
            "VB9)BH3\n" +
            "Q9F)YL8\n" +
            "GHC)23D\n" +
            "5H2)V47\n" +
            "8F6)QNG\n" +
            "15C)2GK\n" +
            "3K5)413\n" +
            "13J)WZS\n" +
            "GT5)DYX\n" +
            "YTP)924\n" +
            "926)5L6\n" +
            "3RG)48M\n" +
            "K3L)2CX\n" +
            "XKN)8DD\n" +
            "3P9)Y8M\n" +
            "Z7P)RN6\n" +
            "T5Q)YGN\n" +
            "67Y)4BN\n" +
            "FMH)4BQ\n" +
            "Q3C)QH8\n" +
            "51Q)LQ2\n" +
            "PF1)CXX\n" +
            "ZQN)63G\n" +
            "MKF)D7N\n" +
            "CWF)V17\n" +
            "G2W)T56\n" +
            "TC3)99Y\n" +
            "KM6)51L\n" +
            "SR1)1C3\n" +
            "SYT)DNP\n" +
            "NWC)JFJ\n" +
            "YZN)W8X\n" +
            "X36)TM3\n" +
            "NGZ)W37\n" +
            "Z8K)88L\n" +
            "T36)GZ4\n" +
            "P3J)9D3\n" +
            "SNP)MDR\n" +
            "PS8)SY7\n" +
            "49D)LTH\n" +
            "R5R)KR5\n" +
            "WX2)829\n" +
            "2LN)9M7\n" +
            "Z8X)ZV7\n" +
            "9ZD)3BB\n" +
            "2YK)TQ7\n" +
            "KM8)YBG\n" +
            "WTQ)DRX\n" +
            "WHX)K7B\n" +
            "L2Z)ZZH\n" +
            "K7X)5F6\n" +
            "P32)Q3G\n" +
            "TBM)KTD\n" +
            "MM1)514\n" +
            "H16)HH6\n" +
            "DBN)NR7\n" +
            "F5C)863\n" +
            "PWC)K86\n" +
            "R8C)1RK\n" +
            "R8G)CB7\n" +
            "F8N)G55\n" +
            "PN2)752\n" +
            "9GN)BKW\n" +
            "68X)LHC\n" +
            "HFM)81R\n" +
            "968)QQX\n" +
            "DQC)ZM4\n" +
            "32W)PVW\n" +
            "4J4)4F6\n" +
            "788)CM5\n" +
            "SCX)MYN\n" +
            "ZPY)7DP\n" +
            "453)QMN\n" +
            "4WP)Q6G\n" +
            "WGM)N88\n" +
            "LCZ)N28\n" +
            "KBJ)J5L\n" +
            "BCM)QL3\n" +
            "6QJ)838\n" +
            "T7Q)V4X\n" +
            "HY6)H93\n" +
            "YR2)MY2\n" +
            "M8X)RK3\n" +
            "7TR)ZQS\n" +
            "6L9)VBP\n" +
            "4R1)D95\n" +
            "WK3)XT6\n" +
            "ZZH)5RJ\n" +
            "KLM)S75\n" +
            "VH8)1DM\n" +
            "Z44)TSP\n" +
            "RLQ)WTG\n" +
            "VFB)9B7\n" +
            "DQJ)SBF\n" +
            "YCT)STJ\n" +
            "QJK)3K5\n" +
            "ZWQ)V4M\n" +
            "M8S)1XZ\n" +
            "15Z)DMM\n" +
            "C61)2VC\n" +
            "F2V)Y9R\n" +
            "SKF)PN7\n" +
            "TYM)F7D\n" +
            "413)WS5\n" +
            "G6D)PTC\n" +
            "HH6)W8Z\n" +
            "6J5)TYH\n" +
            "1T7)T2J\n" +
            "2WC)K3Q\n" +
            "8PL)RFZ\n" +
            "LW5)QLJ\n" +
            "7WL)82P\n" +
            "HFV)ZWQ\n" +
            "6K5)Z82\n" +
            "GWT)HLX\n" +
            "Z63)BRV\n" +
            "XZS)C94\n" +
            "QC7)4J4\n" +
            "82P)SGY\n" +
            "6ZY)HCP\n" +
            "XZM)C12\n" +
            "8PQ)LWF\n" +
            "9FX)NWN\n" +
            "PKT)9GF\n" +
            "5MN)K3H\n" +
            "F7M)Z2H\n" +
            "Y9T)Q3C\n" +
            "M9T)Z3P\n" +
            "D95)F51\n" +
            "266)LDX\n" +
            "LK3)JBP\n" +
            "G3Y)TMV\n" +
            "TJL)H81\n" +
            "TG1)NFT\n" +
            "343)9WV\n" +
            "YYD)XTL\n" +
            "3JX)51F\n" +
            "XQT)JRW\n" +
            "WCP)XCB\n" +
            "7MQ)NGR\n" +
            "SY7)KS8\n" +
            "8YZ)7J5\n" +
            "RSF)ZC5\n" +
            "R3L)P1Y\n" +
            "GDY)KSN\n" +
            "BB7)X3T\n" +
            "8XQ)2YK\n" +
            "WKV)Y55\n" +
            "XTL)PK8\n" +
            "WHS)HPV\n" +
            "CMY)BZK\n" +
            "5F6)JYK\n" +
            "YY3)K6V\n" +
            "75G)7ZX\n" +
            "57K)H6X\n" +
            "4LJ)S3J\n" +
            "63G)CHN\n" +
            "XSB)K4R\n" +
            "2YF)J33\n" +
            "HT2)1C5\n" +
            "SGC)PSX\n" +
            "FGK)QLH\n" +
            "89M)JS1\n" +
            "QZ2)4MQ\n" +
            "CGD)3Y2\n" +
            "SJN)G1G\n" +
            "4KK)2MQ\n" +
            "5R4)YVK\n" +
            "ZQF)WY2\n" +
            "DHB)DVW\n" +
            "V67)5H5\n" +
            "RSL)P2J\n" +
            "LYD)3BR\n" +
            "S3V)FVL\n" +
            "B3H)15X\n" +
            "7V7)Q3D\n" +
            "PD9)XGQ\n" +
            "WWN)LTX\n" +
            "B9L)R8C\n" +
            "YCW)1MY\n" +
            "DWJ)H94\n" +
            "XCX)LR1\n" +
            "TZ5)TG1\n" +
            "G9F)GHC\n" +
            "L38)RGM\n" +
            "S96)HZW\n" +
            "8GJ)V4Z\n" +
            "JMH)9D6\n" +
            "L54)D42\n" +
            "5DG)VP9\n" +
            "3RY)BPM\n" +
            "M2T)TT1\n" +
            "X4D)8RZ\n" +
            "6VZ)GJ6\n" +
            "MS6)KQH\n" +
            "8VQ)RQC\n" +
            "2HM)X4K\n" +
            "8NB)P3T\n" +
            "3T5)551\n" +
            "PN8)1GR\n" +
            "JYY)1KY\n" +
            "G55)1DX\n" +
            "JJ8)B4F\n" +
            "J5D)WCS\n" +
            "1CJ)JLB\n" +
            "YMN)1NV\n" +
            "G76)578\n" +
            "QVM)ZRP\n" +
            "XNS)FZ6\n" +
            "LZ3)8N1\n" +
            "F8D)NJC\n" +
            "CP8)TJ6\n" +
            "MCK)VS2\n" +
            "7NC)WXL\n" +
            "RLK)F5C\n" +
            "5W9)FWB\n" +
            "LHC)TG7\n" +
            "CHV)CMT\n" +
            "QC1)K18\n" +
            "NLQ)HQ5\n" +
            "C17)SGC\n" +
            "4SN)V67\n" +
            "9WV)FLY\n" +
            "DBQ)5HH\n" +
            "L5P)5R9\n" +
            "16M)3Q8\n" +
            "D9R)J92\n" +
            "27Y)ZYC\n" +
            "6PG)FD3\n" +
            "WCM)NKW\n" +
            "FD3)G73\n" +
            "8G6)FCB\n" +
            "FFG)X3Q\n" +
            "QX2)VQR\n" +
            "7ZS)VP6\n" +
            "KQY)DRW\n" +
            "V45)JP2\n" +
            "BHM)6PG\n" +
            "3FB)Z71\n" +
            "9SX)5Q2\n" +
            "6WM)VC4\n" +
            "6FK)66X\n" +
            "SBF)7CW\n" +
            "QLT)KC3\n" +
            "GHY)PWB\n" +
            "HGC)7X1\n" +
            "6K9)TB5\n" +
            "2DY)XT4\n" +
            "TZM)J4N\n" +
            "76F)JCB\n" +
            "X2Q)V5X\n" +
            "MV2)PPM\n" +
            "JS1)G99\n" +
            "1HX)5CB\n" +
            "P3T)VPQ\n" +
            "H56)87D\n" +
            "TQ5)JR3\n" +
            "7KQ)1HX\n" +
            "ZC5)34H\n" +
            "NSV)SSX\n" +
            "DF1)936\n" +
            "WWN)TTM\n" +
            "JP2)9MT\n" +
            "7BD)YCN\n" +
            "M9Y)G6D\n" +
            "PHK)2DY\n" +
            "Y8T)2YF\n" +
            "Z1Y)BFL\n" +
            "LR9)17G\n" +
            "4BS)XKN\n" +
            "8GW)JJ8\n" +
            "LCB)5WC\n" +
            "63X)9GN\n" +
            "NWH)YCZ\n" +
            "3H7)QLT\n" +
            "X6P)1M4\n" +
            "K11)MT1\n" +
            "L5P)861\n" +
            "96G)7K1\n" +
            "NHX)Q9M\n" +
            "3KX)8NB\n" +
            "T26)KL7\n" +
            "YK9)V15\n" +
            "D63)R2V\n" +
            "T25)968\n" +
            "3HB)G7Z\n" +
            "F51)6J8\n" +
            "N3H)GKF\n" +
            "YW6)8BZ\n" +
            "1PN)KZR\n" +
            "X2D)MTJ\n" +
            "LJD)HLS\n" +
            "PT4)81Z\n" +
            "WZF)SWF\n" +
            "92Q)7P7\n" +
            "Q6G)NSR\n" +
            "SGG)WD6\n" +
            "DVL)6M4\n" +
            "XRT)3N9\n" +
            "ZR2)Z88\n" +
            "HPX)YCW\n" +
            "DWD)6K5\n" +
            "PH5)D9L\n" +
            "G9H)HGC\n" +
            "LG2)J6Z\n" +
            "2CX)WQN\n" +
            "HZ1)7FF\n" +
            "NNL)B68\n" +
            "TDL)69K\n" +
            "VHG)3W4\n" +
            "B4J)QZZ\n" +
            "GKF)CXW\n" +
            "RL3)TGN\n" +
            "Z2J)RTZ\n" +
            "VN1)4PC\n" +
            "ZPK)GWT\n" +
            "W8X)D45\n" +
            "XZG)7T3\n" +
            "4KR)VB9\n" +
            "6R6)QR6\n" +
            "KS8)X36\n" +
            "GTT)L54\n" +
            "ZRN)RL3\n" +
            "D6H)F9X\n" +
            "VKX)ZCH\n" +
            "Q28)Q6P\n" +
            "PSX)K6Q\n" +
            "MT1)CGD\n" +
            "739)X74\n" +
            "W44)758\n" +
            "BXP)1SW\n" +
            "VWC)LTK\n" +
            "7G5)L7M\n" +
            "WKB)2VV\n" +
            "R8M)T1X\n" +
            "XT6)PRH\n" +
            "389)F6C\n" +
            "CRK)WLT\n" +
            "1K3)RSF\n" +
            "RFZ)BJN\n" +
            "X3Q)ZBM\n" +
            "NGV)7Q9\n" +
            "81Z)KGZ\n" +
            "29X)4NH\n" +
            "X74)B32\n" +
            "LZR)739\n" +
            "K7V)3H8\n" +
            "D45)J9V\n" +
            "JBK)P3J\n" +
            "RP7)1Q2\n" +
            "C7G)CD2\n" +
            "2B7)9KY\n" +
            "V81)8B7\n" +
            "4LJ)VGV\n" +
            "FSF)Z63\n" +
            "6B3)ZP1\n" +
            "L5Q)T36\n" +
            "2GK)NQG\n" +
            "FWB)D5W\n" +
            "6QJ)KDY\n" +
            "55W)3J9\n" +
            "KVN)KQZ\n" +
            "6BG)B79\n" +
            "Q7N)HWW\n" +
            "5KL)6QJ\n" +
            "CHN)1J5\n" +
            "FBB)3TQ\n" +
            "575)Q8W\n" +
            "4F5)BW9\n" +
            "K4R)YVH\n" +
            "Z82)KM6\n" +
            "LVY)TDL\n" +
            "X9D)55W\n" +
            "L32)211\n" +
            "RBC)3Y1\n" +
            "QMW)2TS\n" +
            "9TX)GBQ\n" +
            "R71)GWY\n" +
            "69K)R5R\n" +
            "SL7)LCZ\n" +
            "1KY)5FP\n" +
            "CR5)8PQ\n" +
            "ZDN)YL2\n" +
            "K9K)YJZ\n" +
            "716)5DG\n" +
            "FZM)M7P\n" +
            "MB4)TVC\n" +
            "JVH)DF1\n" +
            "XWK)3LR\n" +
            "FKT)H56\n" +
            "578)B2P\n" +
            "BJ4)WRZ\n" +
            "TGN)FRK\n" +
            "SWP)Q4Y\n" +
            "1M3)2FY\n" +
            "9DV)YP3\n" +
            "TQ7)KZF\n" +
            "SBF)2R5\n" +
            "351)16M\n" +
            "RTR)GWV\n" +
            "Z5Y)MPT\n" +
            "1BY)RX7\n" +
            "CL2)H97\n" +
            "L5G)DL6\n" +
            "RRJ)1DK\n" +
            "9MD)BS9\n" +
            "NNT)889\n" +
            "T17)3JF\n" +
            "9YQ)WYD\n" +
            "ZJL)JKD\n" +
            "6RN)3QR\n" +
            "ZVD)P2X\n" +
            "21G)NLF\n" +
            "B7X)61N\n" +
            "LY3)RPV\n" +
            "WS8)MPH\n" +
            "67P)Q8F\n" +
            "83M)F3F\n" +
            "XFB)QSQ\n" +
            "FJ5)JKK\n" +
            "K86)575\n" +
            "MSD)CBB\n" +
            "5WC)PW5\n" +
            "NLF)7HX\n" +
            "QZ9)CST\n" +
            "29M)1LB\n" +
            "BY3)4S4\n" +
            "1DK)H55\n" +
            "SPH)WX2\n" +
            "GPP)DXC\n" +
            "FCB)CZW\n" +
            "3HR)KN1\n" +
            "8XQ)3HD\n" +
            "4T6)3P9\n" +
            "XZ8)L92\n" +
            "7GW)GDM\n" +
            "7FM)QX1\n" +
            "K6L)SLL\n" +
            "QF8)3T5\n" +
            "1R7)QT6\n" +
            "3CQ)CVJ\n" +
            "5NY)SZ6";
}
